use rustle_core::MeetingNotes;

pub(crate) fn summarise_with_reason(transcript: &str, reason: impl AsRef<str>) -> MeetingNotes {
    let transcript = cleaned_transcript(transcript);
    let warning = format!(
        "Model output was unavailable or invalid. Full transcript saved instead: {}",
        reason.as_ref()
    );
    let markdown = format!(
        "# Meeting Notes\n\n## Warning\n\n{}\n\n## Transcript\n\n{}\n",
        warning,
        transcript
    );

    MeetingNotes {
        summary: warning,
        key_decisions: Vec::new(),
        action_items: Vec::new(),
        attendees: Vec::new(),
        markdown,
    }
}

fn cleaned_transcript(transcript: &str) -> String {
    let transcript = transcript.trim();
    if transcript.is_empty() {
        "No transcript text was captured.".to_owned()
    } else {
        transcript.to_owned()
    }
}

pub(crate) fn notes_from_markdown(markdown: String) -> MeetingNotes {
    let summary = markdown
        .lines()
        .map(str::trim)
        .find(|line| !line.is_empty() && !line.starts_with('#'))
        .unwrap_or("Summary generated by local AI.")
        .to_owned();

    MeetingNotes {
        summary,
        key_decisions: Vec::new(),
        action_items: Vec::new(),
        attendees: Vec::new(),
        markdown,
    }
}
