use rustle_core::MeetingNotes;

pub(crate) fn summarise_with_reason(_transcript: &str, reason: impl AsRef<str>) -> MeetingNotes {
    let warning = format!(
        "Model output was unavailable or invalid. Transcript draft remains available separately: {}",
        reason.as_ref()
    );
    let markdown = format!("# Meeting Notes\n\n## Warning\n\n{warning}\n");

    MeetingNotes {
        summary: warning,
        key_decisions: Vec::new(),
        action_items: Vec::new(),
        attendees: Vec::new(),
        markdown,
    }
}

pub(crate) fn notes_from_markdown(markdown: String, _transcript: &str) -> MeetingNotes {
    let markdown = strip_generated_transcript(&markdown).trim().to_owned();
    let summary = markdown
        .lines()
        .map(str::trim)
        .find(|line| !line.is_empty() && !line.starts_with('#'))
        .unwrap_or("Summary generated by local AI.")
        .to_owned();

    MeetingNotes {
        summary,
        key_decisions: Vec::new(),
        action_items: Vec::new(),
        attendees: Vec::new(),
        markdown,
    }
}

fn strip_generated_transcript(markdown: &str) -> String {
    let mut output = Vec::new();
    for line in markdown.lines() {
        if is_generated_transcript_heading(line) {
            break;
        }
        output.push(line);
    }

    output.join("\n")
}

fn is_generated_transcript_heading(line: &str) -> bool {
    let trimmed = line.trim();
    if trimmed.is_empty() {
        return false;
    }

    let trimmed = trimmed.trim_start_matches('#').trim();
    let trimmed = trimmed.strip_prefix("**").unwrap_or(trimmed);
    let trimmed = trimmed.strip_suffix("**").unwrap_or(trimmed);
    let trimmed = trimmed.strip_prefix("__").unwrap_or(trimmed);
    let trimmed = trimmed.strip_suffix("__").unwrap_or(trimmed);
    let trimmed = trimmed.trim_end_matches(':').trim();

    trimmed.to_ascii_lowercase().starts_with("transcript")
}
